kind: Namespace
apiVersion: v1
metadata:
  name: lab-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-controller-novnc-deployment
  namespace: lab-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-controller-novnc
  template:
    metadata:
      labels:
        app: lab-controller-novnc
    spec:
      containers:
        - name: lab-orchestrator-novnc
          image: biolachs2/lab_orchestrator_novnc:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-controller-novnc
  name: lab-controller-novnc
  namespace: lab-controller
spec:
  selector:
    app: lab-controller-novnc
  ports:
    - port: 80 # incoming
      name: httpnovnc
      protocol: TCP
      targetPort: 5002 # port in the pod
      nodePort: 30003
  type: NodePort

